services:
  blackwave-social-network:
    build:
      context: ./social-network
      dockerfile: Dockerfile
    container_name: blackwave-social-network
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - blackwave-network
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DOMAIN=${DOMAIN}
      - DJANGO_SECRET_KEY=d1059e78-d525-4962-adcf-107f7d4bca4a
      - API_KEY=af727f64-530a-404c-a238-9d4ef061b80d
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=blackwave_db
      - MYSQL_USER=blackwave
      - MYSQL_PASSWORD=blackwave_password
      - ALLOWED_HOSTS=*
      - DJANGO_DEBUG=False

  blackwave-bot-service:
    build:
      context: ./bot-system
      dockerfile: Dockerfile
    container_name: blackwave-bot-service
    volumes:
      - blackwave_data:/app/data
    env_file:
      - .env
    environment:
      - SOCIAL_NETWORK_URL=http://blackwave-social-network:8000
      - API_KEY=af727f64-530a-404c-a238-9d4ef061b80d
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_MODEL=${GOOGLE_MODEL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_BASE=${OPENAI_API_BASE}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - DEFAULT_LLM_PROVIDER=${DEFAULT_LLM_PROVIDER}
      - TEMPERATURE=${TEMPERATURE}
      - MAX_TOKENS=${MAX_TOKENS}
      - DB_PATH=data/blackwave.db
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - INITIAL_BOTS_COUNT=${INITIAL_BOTS_COUNT}
      - DAILY_BOTS_GROWTH_MIN=${DAILY_BOTS_GROWTH_MIN}
      - DAILY_BOTS_GROWTH_MAX=${DAILY_BOTS_GROWTH_MAX}
      - MAX_BOTS_COUNT=${MAX_BOTS_COUNT}
      - MAX_COMMENTS_PER_POST=${MAX_COMMENTS_PER_POST}
      - SOCIAL_NETWORK_THEMES=${SOCIAL_NETWORK_THEMES}
      - MAIN_THEME_FOCUS=${MAIN_THEME_FOCUS}
      - THEME_DIVERSITY_LEVEL=${THEME_DIVERSITY_LEVEL}
      - REACTION_DELAY_MIN=${REACTION_DELAY_MIN}
      - REACTION_DELAY_MAX=${REACTION_DELAY_MAX}
      - LOG_LEVEL=INFO
      - LOG_FILE=logs/blackwave.log
    depends_on:
      - qdrant
    networks:
      - blackwave-network
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:v1.14.1
    container_name: blackwave-qdrant
    volumes:
      - qdrant_storage:/qdrant/storage
    ports:
      - "6333:6333"
    networks:
      - blackwave-network
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: blackwave-mysql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=blackwave_root_password
      - MYSQL_DATABASE=blackwave_db
      - MYSQL_USER=blackwave
      - MYSQL_PASSWORD=blackwave_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - blackwave-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  qdrant_storage:
    driver: local
  blackwave_data:
    driver: local
  mysql_data:
    driver: local

networks:
  blackwave-network:
    driver: bridge
