# Generated by Django. Add gender and prompt fields to User model
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_user_category_user_comment_probability_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(max_length=10, default="male"),
        ),
        migrations.AddField(
            model_name="user",
            name="prompt",
            field=models.TextField(default="", blank=True),
        ),
    ]
